### ISSUE TITLE
Look into katon

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/local-tld-lib#5]
Looks like a similar project, maybe we can learn something from it?
https://github.com/typicode/katon

I'd still love to have local `.hoodie` domains, at least optionally.

**Comment by janl** [comment]
we have that, not sure what to learn?

**Comment by gr2m** [comment]
I just remember that it wasn't very stable last time I used local-tld-lib, which is why we removed it from Hoodie core? I thought maybe katon has some tricks that we could learn from, but nevermind
